FROM ghcr.io/ranklab-gaming/ranklab-devcontainer:latest

RUN sudo apt-get update
RUN sudo apt-get upgrade -y
RUN sudo apt-get install python3-pip xvfb freerdp2-x11 openssh-client sshpass -y
RUN pip install pip --upgrade
